### PR TITLE
Fixes plus ArduinoJson and latest Sming develop

### PR DESCRIPTION
**Pull request by mikee47**
@verybadsoldier Couple of minor fixes plus latest Sming develop

### CODE REVIEW

**Comment by verybadsoldier** [comment]
Thanks, looking good! Why is `ArduinoJson6` a submodule now as it is part of Sming already anyway, no?

**Comment by mikee47** [comment]
`ArduinoJson` has always been included as a submodule, but it's an optional Component because many projects may not use it, or they may wish to continue using version 5. More info here https://github.com/SmingHub/Sming/pull/1752.

The new build system only pulls in and compiles the Components needed by a project - more details in `Sming/building.md`.

**Comment by mikee47** [comment]
I've got a version of this project using the original ArduinoJson version 5 code which I did for testing purposes. It's in my repo. https://github.com/mikee47/esp_rgbww_firmware, branch `sming-3.9.x-ArduinoJson5`.

**Comment by verybadsoldier** [comment]
> `ArduinoJson` has always been included as a submodule, but it's an optional Component because many projects may not use it, or they may wish to continue using version 5. More info here [SmingHub/Sming#1752](https://github.com/SmingHub/Sming/pull/1752).
> 
> The new build system only pulls in and compiles the Components needed by a project - more details in `Sming/building.md`.

Ahh sorry, my bad. For some reason I thought yesterday that `ArduinoJson6` was added as submodule to this project (while it was already a submodule of `Sming`) with this PR. No idea anymore why I thought that... Thanks!

**Comment by verybadsoldier** [comment]
@mikee47 
I got a working version of the firmware now with current Sming and your changes (just needed one additional minor change in JSON parser handling). Not deeply tested but the basics are working.
Just one thing to sort out in Sming (https://github.com/SmingHub/Sming/issues/547#issuecomment-504679330). I will make a new issue about it tested on latest Sming.
Thanks for your help!

**Pull request merged**
